# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Basic(object):
    def setupUi(self, Basic):
        Basic.setObjectName("Basic")
        Basic.resize(618, 783)
        self.verticalLayout = QtWidgets.QVBoxLayout(Basic)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Basic)
        self.widget.setMinimumSize(QtCore.QSize(600, 320))
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(466, 50, 16, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(410, 290, 21, 20))
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(580, 220, 21, 21))
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(580, 120, 31, 20))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(473, 290, 21, 20))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(442, 290, 21, 20))
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(580, 160, 21, 16))
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(382, 50, 21, 20))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(580, 190, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(510, 50, 31, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 591, 281))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/Tamer/P-img-small.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(412, 50, 21, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(507, 290, 21, 20))
        self.label_17.setObjectName("label_17")
        self.label_15.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_11.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_13.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(Basic)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Basic)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.leHWI = QtWidgets.QLineEdit(Basic)
        self.leHWI.setReadOnly(True)
        self.leHWI.setObjectName("leHWI")
        self.gridLayout_3.addWidget(self.leHWI, 0, 1, 1, 1)
        self.leVER = QtWidgets.QLineEdit(Basic)
        self.leVER.setReadOnly(True)
        self.leVER.setObjectName("leVER")
        self.gridLayout_3.addWidget(self.leVER, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.groupBox = QtWidgets.QGroupBox(Basic)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cbOut0 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut0.sizePolicy().hasHeightForWidth())
        self.cbOut0.setSizePolicy(sizePolicy)
        self.cbOut0.setObjectName("cbOut0")
        self.gridLayout.addWidget(self.cbOut0, 0, 0, 1, 1)
        self.cbOut1 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut1.sizePolicy().hasHeightForWidth())
        self.cbOut1.setSizePolicy(sizePolicy)
        self.cbOut1.setObjectName("cbOut1")
        self.gridLayout.addWidget(self.cbOut1, 1, 0, 1, 1)
        self.cbOut2 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut2.sizePolicy().hasHeightForWidth())
        self.cbOut2.setSizePolicy(sizePolicy)
        self.cbOut2.setObjectName("cbOut2")
        self.gridLayout.addWidget(self.cbOut2, 0, 1, 1, 1)
        self.cbOut3 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut3.sizePolicy().hasHeightForWidth())
        self.cbOut3.setSizePolicy(sizePolicy)
        self.cbOut3.setObjectName("cbOut3")
        self.gridLayout.addWidget(self.cbOut3, 1, 1, 1, 1)
        self.cbOut4 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut4.sizePolicy().hasHeightForWidth())
        self.cbOut4.setSizePolicy(sizePolicy)
        self.cbOut4.setObjectName("cbOut4")
        self.gridLayout.addWidget(self.cbOut4, 0, 2, 1, 1)
        self.cbOut5 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut5.sizePolicy().hasHeightForWidth())
        self.cbOut5.setSizePolicy(sizePolicy)
        self.cbOut5.setObjectName("cbOut5")
        self.gridLayout.addWidget(self.cbOut5, 1, 2, 1, 1)
        self.cbOut6 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut6.sizePolicy().hasHeightForWidth())
        self.cbOut6.setSizePolicy(sizePolicy)
        self.cbOut6.setObjectName("cbOut6")
        self.gridLayout.addWidget(self.cbOut6, 0, 3, 1, 1)
        self.cbOut7 = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOut7.sizePolicy().hasHeightForWidth())
        self.cbOut7.setSizePolicy(sizePolicy)
        self.cbOut7.setObjectName("cbOut7")
        self.gridLayout.addWidget(self.cbOut7, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Basic)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Basic)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.leFosc = QtWidgets.QLineEdit(Basic)
        self.leFosc.setObjectName("leFosc")
        self.gridLayout_2.addWidget(self.leFosc, 1, 1, 1, 1)
        self.leFout = QtWidgets.QLineEdit(Basic)
        self.leFout.setObjectName("leFout")
        self.gridLayout_2.addWidget(self.leFout, 2, 1, 1, 1)
        self.cbOscDisable = QtWidgets.QCheckBox(Basic)
        self.cbOscDisable.setMinimumSize(QtCore.QSize(220, 0))
        self.cbOscDisable.setObjectName("cbOscDisable")
        self.gridLayout_2.addWidget(self.cbOscDisable, 1, 2, 1, 1)
        self.cbAutoStart = QtWidgets.QCheckBox(Basic)
        self.cbAutoStart.setMinimumSize(QtCore.QSize(220, 0))
        self.cbAutoStart.setObjectName("cbAutoStart")
        self.gridLayout_2.addWidget(self.cbAutoStart, 2, 2, 1, 1)
        self.lbDac = QtWidgets.QLabel(Basic)
        self.lbDac.setObjectName("lbDac")
        self.gridLayout_2.addWidget(self.lbDac, 3, 0, 1, 1)
        self.sbDacValue = QtWidgets.QSpinBox(Basic)
        self.sbDacValue.setMaximum(4095)
        self.sbDacValue.setSingleStep(1)
        self.sbDacValue.setProperty("value", 2048)
        self.sbDacValue.setObjectName("sbDacValue")
        self.gridLayout_2.addWidget(self.sbDacValue, 3, 1, 1, 1)
        self.cbOutMode = QtWidgets.QComboBox(Basic)
        self.cbOutMode.setObjectName("cbOutMode")
        self.cbOutMode.addItem("")
        self.cbOutMode.addItem("")
        self.cbOutMode.addItem("")
        self.gridLayout_2.addWidget(self.cbOutMode, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(Basic)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gGps = QtWidgets.QGroupBox(Basic)
        self.gGps.setObjectName("gGps")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gGps)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.gGps)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gGps)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)
        self.le1PPS = QtWidgets.QLineEdit(self.gGps)
        self.le1PPS.setReadOnly(True)
        self.le1PPS.setObjectName("le1PPS")
        self.gridLayout_4.addWidget(self.le1PPS, 1, 1, 1, 1)
        self.leCalcFout = QtWidgets.QLineEdit(self.gGps)
        self.leCalcFout.setReadOnly(True)
        self.leCalcFout.setObjectName("leCalcFout")
        self.gridLayout_4.addWidget(self.leCalcFout, 2, 1, 1, 1)
        self.cbGPSSync = QtWidgets.QCheckBox(self.gGps)
        self.cbGPSSync.setObjectName("cbGPSSync")
        self.gridLayout_4.addWidget(self.cbGPSSync, 0, 0, 1, 1)
        self.lbGpsInfo = QtWidgets.QLabel(self.gGps)
        self.lbGpsInfo.setText("")
        self.lbGpsInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbGpsInfo.setObjectName("lbGpsInfo")
        self.gridLayout_4.addWidget(self.lbGpsInfo, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.gGps)
        spacerItem = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btStore = QtWidgets.QPushButton(Basic)
        self.btStore.setObjectName("btStore")
        self.horizontalLayout_2.addWidget(self.btStore)
        self.btLoad = QtWidgets.QPushButton(Basic)
        self.btLoad.setObjectName("btLoad")
        self.horizontalLayout_2.addWidget(self.btLoad)
        self.btCPLD = QtWidgets.QPushButton(Basic)
        self.btCPLD.setObjectName("btCPLD")
        self.horizontalLayout_2.addWidget(self.btCPLD)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btSet = QtWidgets.QPushButton(Basic)
        self.btSet.setObjectName("btSet")
        self.horizontalLayout_2.addWidget(self.btSet)
        self.btGet = QtWidgets.QPushButton(Basic)
        self.btGet.setObjectName("btGet")
        self.horizontalLayout_2.addWidget(self.btGet)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Basic)
        QtCore.QMetaObject.connectSlotsByName(Basic)

    def retranslateUi(self, Basic):
        _translate = QtCore.QCoreApplication.translate
        Basic.setWindowTitle(_translate("Basic", "ClockTamer Configuration"))
        self.label_5.setText(_translate("Basic", "1"))
        self.label_7.setText(_translate("Basic", "4+"))
        self.label_11.setText(_translate("Basic", "6"))
        self.label_6.setText(_translate("Basic", "0+"))
        self.label_9.setText(_translate("Basic", "5+"))
        self.label_8.setText(_translate("Basic", "4-"))
        self.label_13.setText(_translate("Basic", "7-"))
        self.label_10.setText(_translate("Basic", "3-"))
        self.label_12.setText(_translate("Basic", "7+"))
        self.label_14.setText(_translate("Basic", "0-"))
        self.label_16.setText(_translate("Basic", "3+"))
        self.label_17.setText(_translate("Basic", "5-"))
        self.label_3.setText(_translate("Basic", "HWI:"))
        self.label_4.setText(_translate("Basic", "VER:"))
        self.groupBox.setTitle(_translate("Basic", "Outputs Enabled"))
        self.cbOut0.setText(_translate("Basic", "OUT 0"))
        self.cbOut1.setText(_translate("Basic", "OUT 1"))
        self.cbOut2.setText(_translate("Basic", "OUT 2"))
        self.cbOut3.setText(_translate("Basic", "OUT 3"))
        self.cbOut4.setText(_translate("Basic", "OUT 4"))
        self.cbOut5.setText(_translate("Basic", "OUT 5"))
        self.cbOut6.setText(_translate("Basic", "OUT 6"))
        self.cbOut7.setText(_translate("Basic", "OUT 7"))
        self.label.setText(_translate("Basic", "Fosc"))
        self.label_2.setText(_translate("Basic", "Fout"))
        self.leFosc.setInputMask(_translate("Basic", "09\'999\'999 \\Hz;_"))
        self.leFosc.setText(_translate("Basic", "20\'000\'000 Hz"))
        self.leFout.setInputMask(_translate("Basic", "09\'999\'999 \\Hz;_"))
        self.leFout.setText(_translate("Basic", "52\'000\'000 Hz"))
        self.cbOscDisable.setText(_translate("Basic", "Disable internal oscillator"))
        self.cbAutoStart.setText(_translate("Basic", "Start on power up"))
        self.lbDac.setText(_translate("Basic", "DAC"))
        self.cbOutMode.setItemText(0, _translate("Basic", "DIV4 on Lock"))
        self.cbOutMode.setItemText(1, _translate("Basic", "Int. Oscillator"))
        self.cbOutMode.setItemText(2, _translate("Basic", "DIV4 Always"))
        self.gGps.setTitle(_translate("Basic", "GPS"))
        self.label_18.setText(_translate("Basic", "1PPS Count"))
        self.label_19.setText(_translate("Basic", "Calculated Fout"))
        self.cbGPSSync.setText(_translate("Basic", "Keep in sync with GPS"))
        self.btStore.setText(_translate("Basic", "Store to EEPROM"))
        self.btLoad.setText(_translate("Basic", "Load from EEPROM"))
        self.btCPLD.setText(_translate("Basic", "Update CPLD..."))
        self.btSet.setText(_translate("Basic", "SET"))
        self.btGet.setText(_translate("Basic", "GET"))
import res_rc
